---
- name: change package versions before update
  hosts: all
  become: true
  tasks:
    - name: install
      yum:
        name: chrony=2.1
        state: present
    - name: install
      yum:
        name: grep=2.5.4
        state: present
    - name: install
      yum:
        name: curl=7.19.7
        state: present
    - name: install
      yum:
        name: audit=2.3.1
        state: present
        
                
