---
- name: change package versions before update
  hosts: all
  become: true
  tasks:
  
    - name: install
      yum:
        name: curl-7.61.7.el8.x86_64 
        state: latest 
        allow_downgrade: yes
    
        
                
