---
- name: Print a greeting message
  hosts: all
  gather_facts: false
  vars:
    greeting_name: "{{ greeting_name_input | default('Ansible User') }}"
    greeting_message: "{{ greeting_message_input | default('Have a great day!') }}"
  tasks:
  - name: Print Greeting Message
    ansible.builtin.debug:
      msg: "Hello {{ greeting_name }}, {{ greeting_message }}"
