---
- name: Sending an e-mail
  community.general.mail:
    host: "{{ smtp_host }}"
    port: "{{ smtp_port }}"
    username: "{{ smtp_username }}"
    password: "{{ smtp_password }}"
    from: "{{ from_address }}"
    to: "{{ to_address }}"
    subject: "{{ email_subject }}"
    body: "{{ lookup('template', email_body_template) }}"
  delegate_to: localhost