---
- name: Get a list of all installed packages
  ansible.builtin.yum:
    list: installed
  become: true
  register: installed_result

- name: Use template to Generate CSV File with Available Updates
  template:
    src: index.html.j2
    dest: /home/Documents/packagesreport/index.html
  delegate_to: localhost
  run_once: True