---
- name: edit hosts file to resolve the sat ec2_server 
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {{ sat_server_ip }} {{ sat_server_hostname }}

- name: make sure subscription-manager is present
  ansible.builtin.dnf:
    name: subscription-manager
    state: present
  ignore_errors: yes

- name: clear subscription and identity data
  ansible.builtin.command: subscription-manager clean
  become: true

- name: install the proper certificates for client-satellite server communication
  ansible.builtin.dnf:
    name: http://{{ sat_server_hostname }}/pub/katello-ca-consumer-latest.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: Register host to {{ sat_server_hostname }} using Activation Key {{ sat_activation_key }} and Org {{ sat_org_id }}
  community.general.redhat_subscription:
    state: present
    server_insecure: 1
    activationkey: "{{ sat_activation_key }}"
    org_id: "{{ sat_org_id }}"
    force_register: true

- name: Make sure Repository management is enabled in rhsm.conf 
  ansible.builtin.lineinfile:
    path: /etc/rhsm/rhsm.conf
    regexp: '^manage_repos'
    line: manage_repos = 1



- name: Enable satellite tools repo provided by the content view
  community.general.rhsm_repository:
    name: "{{ sat_contentview_tools_repo }}"

- name: install Katello Host Tools
  ansible.builtin.dnf:
    name: katello-host-tools
    state: present

    